services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_started
    networks:
      - backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - /usr/src/app/node_modules
      - ./src:/usr/src/app/src
  postgres:
    build:
      context: .
      dockerfile: Db.Dockerfile
    networks:
      - backend
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PORT_LISTEN=${POSTGRES_PORT_LISTEN}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT_LISTEN}
    expose:
      - ${POSTGRES_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d home_library']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    volumes:
      - PGDATA:/var/lib/postgresql/data
volumes:
  PGDATA:
networks:
  backend:
    driver: bridge